<?php

/** @var \AHT\SaleAgent\Block\Template $block */
?>
<h1>Modal Test Page</h1>
<div class="template">
    <button id="button1">
        <span><?= $block->escapeHtml(__('Open Modal')) ?></span>
    </button>

    <button id="button2">
        <span><?= $block->escapeHtml(__('Open Magento Login Modal')) ?></span>
    </button>

    <button id="button3">
        <span><?= $block->escapeHtml(__('Open Custom Login Modal')) ?></span>
    </button>

    <div id="modal1">
        <div class="modal-body-content">
            <h2><?= $block->escapeHtml(__('Title')) ?></h2>
            <p><?= $block->escapeHtml(__('Content')) ?></p>
        </div>
    </div>

    <div id="modal2">
        <div class="modal-body-content">
            <div class="login-modal" id='authentication-popup-template' data-bind="scope: 'authentication-popup'">
                <!-- ko template: getTemplate() -->
                <!-- /ko  -->
                <script type="text/x-magento-init">
                    {
                        "#authentication-popup-template": {
                            "Magento_Ui/js/core/app": {
                                "components": {
                                    "authentication-popup": {
                                        "component": "AHT_SaleAgent/js/authentication-popup",
                                        "template" : "AHT_SaleAgent/authentication-popup",
                                        "children": {
                                            "messages":{
                                                "component":"Magento_Ui/js/view/messages",
                                                "displayArea":"messages"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                </script>
            </div>
        </div>
    </div>

    <div id="modal3">
        <div class="modal-body-content">
            <h2><?= $block->escapeHtml(__('Title')) ?></h2>
            <p><?= $block->escapeHtml(__('Content')) ?></p>
        </div>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        "Magento_Ui/js/modal/modal"
    ], function($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            title: 'Main title',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function() {
                    this.closeModal();
                }
            }]
        };
        console.log($.mage);
        var popup1 = modal(options, $('#modal1'));

        var popup2 = modal({
            type: 'popup',
            responsive: true,
            title: 'Login Modal',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function() {
                    this.closeModal();
                }
            }]
        }, $('#modal2'));

        var popup3 = modal(options, $('#modal3'));
        $("#button1").click(function() {
            $('#modal1').modal('openModal');
        });

        $("#button2").click(function() {
            $('#modal2').modal('openModal');
        });

        $("#button3").click(function() {
            $('#modal3').modal('openModal');
        });
    })
</script>