<?php

/** @var \AHT\SaleAgent\Block\Template $block */
?>

<div id='fastorder_template' data-bind="scope: 'fastorder'">
    <!-- ko template: getTemplate() -->
    <!-- /ko  -->
    <script>
        window.configs = <?= /* @escapeNotVerified */ \Zend_Json::encode($block->getConfig()) ?>
    </script>
    <script type="text/x-magento-init">
        {
        "#fastorder_template": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "fastorder": {
                        "component": "AHT_SaleAgent/js/fastorder"
                    }
                }
            }
        }
    }
</script>
</div>


<script>
    require([
        'mage/url',
        'Magento_Ui/js/block-loader'
    ], function(url, blockLoader) {
        blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
        return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl(); ?>');
    })
</script>