<?php

/** @var \AHT\SaleAgent\Block\Template $block */
$products = $block->getProductOrder();
$symbol = $block->getSymbol();
?>

<table class="table-scroll small-first-col">
    <thead>
        <tr>
            <th>SKU</th>
            <th>PRODUCT</th>
            <th>QTY</th>
            <th>SUBTOTAL</th>
        </tr>
    </thead>
    <tbody class="body-half-screen">
        <?php foreach ($products as $product) : ?>
            <tr data-product-id="<?= $product->getId() ?>">
                <td><?= $product->getData('sku') ?></td>
                <td>
                    <div class="product__detail">
                        <div class="product__detail--left">
                            <img src='<?= $block->getUrlImage($product) ?>' alt="<?= $product->getData('name') ?>">
                        </div>
                        <div class="product__detail--right">
                            <div class="name"><?= $product->getData('name') ?></div>
                            <div class="product__detail">
                                <span><?= $block->getPrice($product) ?></span>
                            </div>
                        </div>
                        <div class="product__detail--tool">
                            <span class="icon-trash" data-value='<?= $product->getId() ?>'></span>
                        </div>
                    </div>
                </td>
                <td>
                    <?php if ($product->getData('type_id') == 'simple') : ?>
                        <div class="qty">
                            <button data-button-qty="-1">-</button>
                            <input type="number" value="1" data-qty-max="<?= $block->getMaxStock($product) ?>" data-product-baseprice="<?= $block->getPrice($product) ?>" value="<?= $block->getQty($product) ?>">
                            <button data-button-qty="1">+</button>
                        </div>
                    <?php else : ?>
                        <p>just product simple</p>
                    <?php endif ?>
                </td>
                <td>
                    <p>
                        <span><?= $block->getSymbol() ?></span> <span class="subtotal_price"></span>
                    </p>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
    <tfoot>
        <tr>
            <th></th>
            <th>
                <p>Filter lines Number: <span><?= count($products) ?></span></p>
            </th>
            <th>
                <p>Total Qty: <span class="total_qty" data-total-qty="0"></span></p>
            </th>
            <th>
                <p>Sub Total:<span>$</span> <span class='total_price' data-total-price="0"></span></p>
            </th>
        </tr>
    </tfoot>
</table>
<div class="add-cart">
    <button type="submit">
        Add cart
    </button>
</div>